### Generated by Winemaker 0.7.6


SRCDIR                = .
SUBDIRS               =
DLLS                  =
EXES                  = stars.exe



### Common settings

CEXTRA                = -O0 -W  \
			-mno-cygwin -m32 -w
CXXEXTRA              = -O0 -W  \
			-mno-cygwin -m32 -w
RCEXTRA               =
DEFINES               = -DWIN32 -D_DEBUG -D_WINDOWS 
INCLUDE_PATH          = $(MFC_INCLUDE_PATH)
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =  -lodbc32 -lodbccp32 -lwinmm -ldsound -ldxerr9 -ld3d9 -d3dx9 -ldsound -ldinput -lxinput -ld3dim -ld3dxof -ld3dcompiler


### stars.exe sources and settings

stars_exe_MODULE      = stars.exe
stars_exe_C_SRCS      =
stars_exe_CXX_SRCS    = Stars.cpp \
			dsutil.cpp \
			dxutil.cpp \
			func.cpp
stars_exe_RC_SRCS     = Stars.rc
stars_exe_LDFLAGS     = -mwindows \
			-mno-cygwin -m32
stars_exe_DLL_PATH    = $(MFC_LIBRARY_PATH)
stars_exe_DLLS        = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
stars_exe_LIBRARY_PATH= $(MFC_LIBRARY_PATH)
stars_exe_LIBRARIES   = uuid

stars_exe_OBJS        = $(stars_exe_C_SRCS:.c=.o) \
			$(stars_exe_CXX_SRCS:.cpp=.o) \
			$(stars_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(stars_exe_C_SRCS)
CXX_SRCS              = $(stars_exe_CXX_SRCS)
RC_SRCS               = $(stars_exe_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(EXES:%=%.so)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(EXES:%=%.so) $(EXES:%.exe=%)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(stars_exe_MODULE).so: $(stars_exe_OBJS)
	$(CXX) $(stars_exe_LDFLAGS) -o $@ $(stars_exe_OBJS) $(stars_exe_LIBRARY_PATH) $(DEFLIB) $(stars_exe_DLLS:%=-l%) $(stars_exe_LIBRARIES:%=-l%)


